# General
log_dir="/var/log/mediapi"

# Access Point
ap_con_name="AccessPoint"
ap_host=192.168.4.1
wifi_interface=wlan0
## In minutes
ap_start_delay_after_disconnect=10
ap_ssid=
ap_ssid_use_hostname=True

# Webapp
host=0.0.0.0
port=80

# Locale
locale=de-DE

# End