network:
  network_manager:
    script_path: 'scripts/network_manager.sh'
    timeout: 3
    default_interface: 'eth0'
  system_proxy:
    script_path: 'scripts/system_proxy.sh'
    timeout: 3

system:
  auto-update: !!bool "true"

app:
  # Flask App Config
  # Default 127.0.0.1
  HOST: "127.0.0.1"
  PORT: 8080

  # This is not required when nginx SSL is used
  SSL_ENABLED: !!bool "false"
  # Tries to use them. If they do not exist it will fall back to self-signed
  SSL_CERT_PATH: 'cert.pem'
  SSL_KEY_PATH: 'key.pem'

  DEBUG: True
  PROPAGATE_EXCEPTIONS: True

  LOGGING: "info"


  # Supported languages
  LANGUAGES: ['en', 'de']
  # https://python-babel.github.io/flask-babel/
  BABEL_DEFAULT_LOCALE: 'en'
  BABEL_TRANSLATION_DIRECTORIES: 'translations'
  BABEL_DOMAIN: 'messages'

  auto-update: true

policies:
  max_device_name_len: 50

bluetooth:
  config_path: "../bt/config.env"
  install_path: "../bt/install.sh"
  uninstall_path: "../bt/uninstall.sh"
  deploy_path: "../bt/deploy.sh"
  deploy_on: ['DEVICE_CLASS', 'DISCOVERABLE', 'AUDIO_DEVICE', 'DEVICE_NAME']
  device_class_mapping: {
    "0x200414": 'Loudspeaker',
    "0x200418": 'Headphones',
    "0x20041C": 'Portable Audio'
  }

shairport-sync:
  config_path: "../modules/shairport-sync/config.env"
  install_path: "../modules/shairport-sync/install.sh"
  uninstall_path: "../modules/shairport-sync/uninstall.sh"
  update_path: "../modules/shairport-sync/update.sh"

gmrender-resurrect:
  config_path: "../modules/gmrender-resurrect/config.env"
  install_path: "../modules/gmrender-resurrect/install.sh"
  uninstall_path: "../modules/gmrender-resurrect/uninstall.sh"
  update_path: "../modules/gmrender-resurrect/update.sh"

nginx:
  config_path: "../modules/nginx/config.env"
  install_path: "../modules/nginx/install.sh"
  uninstall_path: "../modules/nginx/uninstall.sh"
  detect_path: "../modules/nginx/detect_installation.sh"
  update_apt_available_path: "../modules/nginx/update_apt_available.sh"
  update_apt_path: "../modules/nginx/update_apt.sh"